pivotal-legacy/homebrew-tap

cloudfoundry-cli.rb

bump cli version to v6.9.0

---

cloudfoundry-cli.rb

bump cli version to v6.10.0

---

README.md
git-pair.rb

Because I don't like to install gems globally.

Add git-pair formula

---

cloudfoundry-cli.rb

Sorry about these repeated PRs. We've been monkeying around with our build and release pipeline, and it's been rebuilding the release tar.

Fixed broken sha again. Should be stable now.

---

cloudfoundry-cli.rb

bump CLI version to v6.11.2

---

bosh-init.rb

Does what it says on the tin.
cc/ @cppforlife

Add formula for bosh-init

---

cloudfoundry-cli.rb

Bump CLI to v6.11.3

---

cloudfoundry-cli.rb

Bump CLI to v6.12.0

---

cloudfoundry-cli.rb

Bump CLI to v6.12.2

---

cloudfoundry-cli.rb

Signed-off-by: Kris Hicks <khicks@pivotal.io>

Bump CLI to v6.13.0

---

bosh-init.rb
cloudfoundry-cli.rb

Bump bosh-init to 0.0.81 and cf cli to 6.16.0

Update Bosh-Init and CF cli

---

greenplum-db.rb

Add notice to clarify the level of support from this homebrew formula.

Add support notice

---

greenplum-db.rb

Signed-off-by: Scott Kahler <skahler@pivotal.io>

Bump version to 5.0.0 beta 6

---

gp-xerces.rb
gporca.rb
greenplum-db.rb

This added two new formula for dependencies:
- gporca.rb
- gp-xerces.rb
Signed-off-by: Scott Kahler <skahler@pivotal.io>

Build greenplum-db with gporca

---

git-author.rb

Co-authored-by: Xin Zhang <xzhang@pivotal.io>
Co-authored-by: Todd Sedano <tsedano@pivotal.io>

Add git-author homebrew formula

---

git-author.rb
springxd.rb
sqlfire.rb

Replaces <<-EOS.undent with <<~EOS

---

pace-cli.rb

PA tool for creating static web sites used to run workshops.

Add pace command line tool to tap

---

pace-cli.rb

bump PACE cli version to v0.6

---

pace-cli.rb

bump to v0.9

---

pace-cli.rb

bump pace-cli to v1.0

---

tcserver.rb

This updates tc Server to version 4.0.7.RELEASE

Update tc Server to 4.0.7 version

---

pace-cli.rb

Updated theme and made error messages more intuitive.

updated pace-cli.rb to version 1.5

---

tcserver.rb

This is the update for the latest tc Server release.

Update tc Server to 4.0.8

---

tcserver.rb

Update for tc Server 4.0.8

---

tcserver.rb

This is the update for tc Server 4.0.11

Update for tc Server 4.0.11

---

tcserver.rb

This change updates the tcserver tap to use the latest release of tc Server which is 4.1.0

Update to tc Server 4.1.0

---

tcserver.rb

Update for tc Server 4.1.1

---

tcserver.rb

This updates to tc Server 4.1.2

Update tcserver.rb for 4.1.2

---

tcserver.rb

This updates tcserver to 4.1.3

Update tcserver.rb for 4.1.3

---

tcserver.rb

Update for tc Server release 4.1.6

Update for tc Server release 4.1.6

---

tcserver.rb

This updates to tc Server 4.1.10

Update to tc Server 4.1.10

---

README-tcserver.md
README.md
tcserver.rb

This change will cause brew to error out upon upgrade command being ran. Displaying message to user

Update tcserver.rb to decommission homebrew tap
